name: kantor_tukan
description: Kantor Tukan.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.3+3

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  freezed: 1.1.0
  mockito: ^5.0.17
  flutter_bloc: ^8.0.1
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  google_sign_in: ^5.2.3
  freezed_annotation: ^1.1.0
  injectable_generator: ^1.5.2
  injectable: ^1.5.3
  another_flushbar: ^1.10.28
  uuid: ^3.0.5
  flutter_native_splash: ^2.0.1+1
  bloc_test: ^9.0.2
  cloud_firestore: ^3.1.7
  kt_dart: ^0.10.0
  json_serializable: ^6.1.4
  json_annotation: ^4.4.0
  data_connection_checker: ^0.3.4
  http: ^0.13.4
  internet_connection_checker: ^0.0.1+3
  percent_indicator: ^4.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_ringtone_player: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  lint: ^1.7.2


flutter:
  uses-material-design: true
  assets:
    - D:\Flutter\kantor_tukan\assets\logo_tukan.png
    - assets/wymiana_calc.png

flutter_native_splash:
  color: "#f8f4f3"
  image: D:\Flutter\kantor_tukan\assets\logo_tukan.png
  android: true
  ios: false
  android12: true
  android_gravity: center


flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
